### ISSUE TITLE
Running grunt on OS X results in error

### ISSUE THREAD

**Issue by ghost** [2016-01-cit337/client#1]
Error: Cannot find where you keep your Bower packages. Use --force to continue.
Aborted due to warnings.

**Comment by ghost** [comment]
According to [StackOverflow](http://stackoverflow.com/questions/22367837/what-is-causing-grunt-serve-to-throw-no-bower-components-found#22666156), I may just need to install Ruby.

**Comment by ghost** [comment]
Try running `bower install` from home.  It looks like OU's network is blocking some needed traffic.
https://gist.github.com/mbroe/af4a315c91bf6f37d4a6

**Comment by ghost** [comment]
I was able to run it successfully in Fedora 23 by installing ... a lot of packages.  I don't know exactly which ones.

**Comment by easterlyme** [comment]
For reference, to install of the npm module dependencies, right click the package.json and "Run 'npm update'"

**Comment by easterlyme** [comment]
Then after you have all the node modules installed, you can run `bower install` in the project folder.

**Comment by ghost** [comment]
@crreilly's [document](https://docs.google.com/document/d/1U1IghDaGHFzGHUAMYQo2XhEUWIH--kKfwVVeUHEjFGg) was really helpful for me in setting up my environment.  I added a couple of items to it from the class slides, as well.  Either way, it's running beautifully now.
